/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;

import BackEnd.Perritos;
import BackEnd.PerritosDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class VistaPerritosCrear extends javax.swing.JFrame {

    /**
     * Creates new form VistaPerritos
     */
    public VistaPerritosCrear() {
        initComponents();
        
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRaza = new javax.swing.JLabel();
        txtfRaza = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtfNombre = new javax.swing.JTextField();
        lblColor = new javax.swing.JLabel();
        txtfColor = new javax.swing.JTextField();
        txtfPeso = new javax.swing.JTextField();
        lblPeso = new javax.swing.JLabel();
        lblAltura = new javax.swing.JLabel();
        txtfAltura = new javax.swing.JTextField();
        lblDueno = new javax.swing.JLabel();
        txtfDueno = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        lblRaza.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblRaza.setText("Raza");
        getContentPane().add(lblRaza);
        lblRaza.setBounds(620, 120, 160, 40);

        txtfRaza.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtfRaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfRazaActionPerformed(evt);
            }
        });
        getContentPane().add(txtfRaza);
        txtfRaza.setBounds(620, 170, 310, 40);

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNombre.setText("Nombre");
        getContentPane().add(lblNombre);
        lblNombre.setBounds(180, 120, 160, 40);

        txtfNombre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(txtfNombre);
        txtfNombre.setBounds(180, 170, 310, 40);

        lblColor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblColor.setText("Color");
        getContentPane().add(lblColor);
        lblColor.setBounds(180, 270, 160, 40);

        txtfColor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(txtfColor);
        txtfColor.setBounds(180, 320, 310, 40);

        txtfPeso.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtfPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfPesoActionPerformed(evt);
            }
        });
        getContentPane().add(txtfPeso);
        txtfPeso.setBounds(620, 320, 310, 40);

        lblPeso.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPeso.setText("Peso");
        getContentPane().add(lblPeso);
        lblPeso.setBounds(620, 270, 160, 40);

        lblAltura.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblAltura.setText("Altura");
        getContentPane().add(lblAltura);
        lblAltura.setBounds(180, 410, 160, 40);

        txtfAltura.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(txtfAltura);
        txtfAltura.setBounds(180, 460, 310, 40);

        lblDueno.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDueno.setText("Dueño");
        getContentPane().add(lblDueno);
        lblDueno.setBounds(630, 410, 160, 40);

        txtfDueno.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(txtfDueno);
        txtfDueno.setBounds(630, 460, 310, 40);

        btnCrear.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnCrear.setText("Crear Perrito");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrear);
        btnCrear.setBounds(410, 570, 310, 50);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtfRazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfRazaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfRazaActionPerformed

    private void txtfPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfPesoActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        String nombre = txtfNombre.getText();
        String raza = txtfRaza.getText();
        String color = txtfColor.getText();
        double peso = Double.valueOf(txtfPeso.getText());
        double altura = Double.valueOf(txtfAltura.getText());
        String dueno = txtfDueno.getText();
        
        Perritos perrito = new Perritos(nombre, raza, color, peso, altura, dueno);
        PerritosDAO perritosDAO = new PerritosDAO();
        int resultado = perritosDAO.insertarPerrito(perrito);
        
        if(resultado == 1){
            System.out.println("El perrito se creo exitosamente");
            VistaPerritos vistaPerritos = new VistaPerritos();
            vistaPerritos.setVisible(true);
            dispose();
        }else{
            System.out.println("No se pudo crear el perrito");
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPerritosCrear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPerritosCrear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPerritosCrear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPerritosCrear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPerritosCrear().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JLabel lblAltura;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblDueno;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblRaza;
    private javax.swing.JTextField txtfAltura;
    private javax.swing.JTextField txtfColor;
    private javax.swing.JTextField txtfDueno;
    private javax.swing.JTextField txtfNombre;
    private javax.swing.JTextField txtfPeso;
    private javax.swing.JTextField txtfRaza;
    // End of variables declaration//GEN-END:variables
}
