/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;

import BackEnd.Perritos;
import BackEnd.PerritosDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class VistaPerritos extends javax.swing.JFrame {

    /**
     * Creates new form VistaPerritos
     */
    public VistaPerritos() {
        initComponents();
        
        DefaultTableModel model = (DefaultTableModel) tblPerritos.getModel();
        PerritosDAO perritosDAO = new PerritosDAO();
        List<Perritos> listaPerritos = perritosDAO.obtenerTodosLosPerritos();
        
        for(Perritos perrito : listaPerritos){
             model.addRow(new Object[]{
                    perrito.getIdPerrito(),
                    perrito.getNombre(),
                    perrito.getRaza(),
                    perrito.getColor(),
                    perrito.getPeso(),
                    perrito.getAltura(),
                    perrito.getDueno()

                });
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVer = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPerritos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        btnVer.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Videos\\Veterinaria\\src\\main\\java\\Imagenes\\Ver.png")); // NOI18N
        getContentPane().add(btnVer);
        btnVer.setBounds(50, 230, 81, 82);

        btnActualizar.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Videos\\Veterinaria\\src\\main\\java\\Imagenes\\Actualizar.png")); // NOI18N
        getContentPane().add(btnActualizar);
        btnActualizar.setBounds(50, 330, 81, 75);

        btnBorrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Videos\\Veterinaria\\src\\main\\java\\Imagenes\\Borrar.png")); // NOI18N
        getContentPane().add(btnBorrar);
        btnBorrar.setBounds(50, 430, 81, 75);

        btnCrear.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Videos\\Veterinaria\\src\\main\\java\\Imagenes\\Crear.png")); // NOI18N
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrear);
        btnCrear.setBounds(50, 130, 81, 80);

        tblPerritos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id Perrito", "Nombre", "Raza", "Color", "Peso", "Altura", "Dueño"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPerritos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(170, 110, 820, 402);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        VistaPerritosCrear vistaPerritosCrear = new VistaPerritosCrear();
        vistaPerritosCrear.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btnCrearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPerritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPerritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPerritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPerritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPerritos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnVer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPerritos;
    // End of variables declaration//GEN-END:variables
}
